version: '3.8'
services:
  devcontainer:
    build:
     context: .
     dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    network_mode: service:db
    command: sleep infinity

  db:
    image: mariadb:latest
    restart: unless-stopped
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "mariadb"
      MYSQL_USER: "mariadb"
      MYSQL_DATABASE: "mariadb"
      MYSQL_PASSWORD: "mariadb"

volumes:
  mariadb-data: